<?php

return [
    'validation' => [
        'messages' => [
            'required' => 'O campo :attribute é obrigatório.',
            'string' => 'O campo :attribute deve ser uma string.',
            'between' => 'O campo :attribute deve estar entre :min e :max.',
            'min' => 'O campo :attribute deve ter pelo menos :min caracteres.',
            'max' => 'O campo :attribute não pode ter mais de :max caracteres.',
            'unique' => 'O :attribute informado já está em uso.',
            'email' => 'O campo :attribute deve ser um endereço de e-mail válido.',
            'exists' => 'O campo :attribute não existe.',
            'date' => 'O campo :attribute deve ser uma data válida.',
            'boolean' => 'O campo :attribute deve ser true ou false.',
            'numeric' => 'O campo :attribute deve ser um número.',
            'array' => 'O campo :attribute deve ser um array.',
            'in' => 'O campo :attribute deve ser um dos seguintes valores: :values.',
            'date_format' => 'O campo :attribute deve estar no formato :format.',
            'timezone' => 'O campo :attribute deve ser um fuso horário válido.',
            'file' => 'O campo :attribute deve ser um arquivo.',
            'image' => 'O campo :attribute deve ser uma imagem.',
            'mimes' => 'O campo :attribute deve ser um arquivo do tipo: :values.',
            'mimetypes' => 'O campo :attribute deve ser um arquivo do tipo: :values.',
            'dimensions' => 'O campo :attribute deve ter dimensões válidas.',
            'active_url' => 'O campo :attribute deve ser uma URL ativa.',
            'url' => 'O campo :attribute deve ser uma URL válida.',
            'ip' => 'O campo :attribute deve ser um endereço IP válido.',
            'ipv4' => 'O campo :attribute deve ser um endereço IPv4 válido.',
            'ipv6' => 'O campo :attribute deve ser um endereço IPv6 válido.',
            'json' => 'O campo :attribute deve ser uma string JSON válida.',
            'regex' => 'O campo :attribute deve corresponder ao formato especificado.',
            'confirmed' => 'O campo :attribute de confirmação não corresponde.',
            'different' => 'O campo :attribute deve ser diferente de :other.',
            'required_if' => 'O campo :attribute é obrigatório quando :other é :value.',
            'required_unless' => 'O campo :attribute é obrigatório a menos que :other esteja em :values.',
            'required_with' => 'O campo :attribute é obrigatório quando :values está presente.',
            'required_with_all' => 'O campo :attribute é obrigatório quando todos os :values estão presentes.',
            'required_without' => 'O campo :attribute é obrigatório quando :values não está presente.',
            'required_without_all' => 'O campo :attribute é obrigatório quando nenhum dos :values está presente.',
            'same' => 'O campo :attribute e :other devem corresponder.',
            'size' => 'O campo :attribute deve ter exatamente :size caracteres.',
            'starts_with' => 'O campo :attribute deve começar com um dos seguintes valores: :values.',
            'ends_with' => 'O campo :attribute deve terminar com um dos seguintes valores: :values.',
            'nullable' => 'O campo :attribute pode ser nulo.',
            'present' => 'O campo :attribute deve estar presente, mas pode estar vazio.',
            'filled' => 'O campo :attribute deve ter um valor.',
            'distinct' => 'O campo :attribute deve ter valores distintos.',
            'prohibited' => 'O campo :attribute é proibido.',
            'prohibited_if' => 'O campo :attribute é proibido quando :other é :value.',
            'prohibited_unless' => 'O campo :attribute é proibido a menos que :other esteja em :values.',
            'prohibits' => 'O campo :attribute proíbe :other de estar presente.',
            'accepted' => 'O campo :attribute deve ser aceito.',
            'accepted_if' => 'O campo :attribute deve ser aceito quando :other for :value.',
            'active_url' => 'O campo :attribute deve ser uma URL ativa.',
        ],
    ],
];